// <auto-generated />
namespace Books_MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddDataAndCreatePage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDataAndCreatePage));
        
        string IMigrationMetadata.Id
        {
            get { return "202206050552225_AddDataAndCreatePage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
